/*
 * DO NOT EDIT THIS FILE.  It contains C->PostScript communication
 * definitions that were automatically generated from diffs
 */

#if !defined(CONST)
#    if defined(__cplusplus) || defined(c_plusplus) || defined(__STDC__)
#	define CONST	const
#    else
#	define CONST
#    endif
#endif



#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif
