# Get the directory in which this Makefile fragment resides.
HELPMSG_SRCDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

HELPMSG_APP_SRCDIR := $(HELPMSG_SRCDIR)
HELPMSG_APP_OBJDIR := $(BBS_OBJDIR)/helpmsg
BBS_LOCALDIR := $(HELPMSG_APP_SRCDIR)/../../include

HELPMSG_APP_PROD := helpmsg

HELPMSG_APP_SRCS := helpmsg.c

HELPMSG_APP_CFLAGS := -I$(HELPMSG_APP_SRCDIR)/../bbs

$(eval $(call create_bbs_app_rules,HELPMSG_APP))

HELPMSG_DAT := $(HELPMSG_APP_OBJDIR)/helpmsg.dat
HELPMSG_IDX := $(HELPMSG_APP_OBJDIR)/helpmsg.idx

HELPMSG_CORE := $(HELPMSG_APP_SRCDIR)/helpmsg.txt
HELPMSG_LOCAL := $(BBS_LOCALDIR)/local-helpmsg.txt

$(HELPMSG_DAT) $(HELPMSG_IDX): $(HELPMSG_APP) $(HELPMSG_CORE) $(HELPMSG_LOCAL)
	$(HELPMSG_APP) \
		$(HELPMSG_CORE) \
		$(HELPMSG_LOCAL) \
		$(HELPMSG_DAT) \
		$(HELPMSG_IDX)

HELPMSG_MESSAGES: $(HELPMSG_DAT) $(HELPMSG_IDX)

HELPMSG_INSTALL: $(HELPMSG_DAT) $(HELPMSG_IDX)
	install -d $(BBS_DIR)/etc
	cp $(HELPMSG_DAT) $(BBS_DIR)/etc
	cp $(HELPMSG_IDX) $(BBS_DIR)/etc

BBS_PRODUCTS += $(HELPMSG_DAT) $(HELPMSG_IDX)
BBS_CLEAN_TARGETS += HELPMSG_APP_CLEAN
BBS_INSTALL_TARGETS += HELPMSG_INSTALL
