include ../../include/config.mk
include ../bbs.mk

PROD = b_bidd
OBJS =	main.o read.o hash.o date.o parse.o write.o edit.o
CFILES =	main.c read.c hash.c date.c parse.c write.c edit.c
HDRS = bid.h
SUPPORT = Makefile

include ../common.mk
