THIS_SRCDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

all: GATEWAY_APP

include $(THIS_SRCDIR)/../../top.mk

GATEWAY_APP: $(GATEWAY_APP)

clean: GATEWAY_APP_CLEAN
install: GATEWAY_APP_INSTALL
