include ../../include/config.mk
include ../bbs.mk

PROD = b_gated
OBJS =	main.o age.o file.o date.o parse.o mail.o guess.o
#AGE_OBJS =	age.o file.o date.o
CFILES =	main.c file.c date.c parse.c mail.c guess.c age.c
HDRS = gate.h
SUPPORT = Makefile

include ../common.mk
