BBS_CONFIG_SRCDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

include $(BBS_CONFIG_SRCDIR)/site_config.mk

ifndef BBS_SYSLOG_FACILITY
  BBS_SYSLOG_FACILITY=LOG_LOCAL1
endif

ifdef BBS_DEBUG
  BBS_OPT_CFLAGS = -g
  BBS_OPT_LDFLAGS = -g
  QA_OPT_LDFLAGS = -g
else
  BBS_OPT_CFLAGS = -O3
endif

BBS_O_CFLAGS += -Werror -I$(TOP_SRCDIR)/include -DBBS_DIR=\"$(BBS_DIR)\"

ifneq ($(ENABLE_DECTALK),0)
  BBS_O_CFLAGS += -DDECTALK
endif

ifneq ($(ENABLED_DTMF),0)
  BBS_O_CFLAGS += -DDTMF
endif

ifdef SUNOS
  BBS_O_CFLAGS += -DSUNOS
  HAVE_TIMEGM=1
  HAVE_INETNTOA_R=1
endif
ifdef FREEBSD
  HAVE_TIMEGM=1
  HAVE_TERMIOS=1
  BBS_O_LDFLAGS+= -lcompat
  QA_OPT_LDFLAGS = -lcompat
  HAVE_REGCOMP=1
  HAVE_INETNTOA_R=1
  HAVE_LINGER_STRUCT=1
endif
ifdef OPENBSD
  HAVE_TIMEGM=1
  HAVE_TERMIOS=1
  HAVE_REGCOMP=1
  HAVE_LINGER_STRUCT=1
endif
ifdef MACOSX
  HAVE_TIMEGM=1
  HAVE_TERMIOS=1
  HAVE_REGCOMP=1
  HAVE_LINGER_STRUCT=1
  BBS_O_CFLAGS+= -Wno-deprecated-declarations
endif

ifdef HAVE_TIMEGM
  BBS_O_CFLAGS += -DHAVE_TIMEGM
endif
ifdef HAVE_TERMIOS
  BBS_O_CFLAGS += -DHAVE_TERMIOS
endif
ifdef HAVE_REGCOMP
  BBS_O_CFLAGS += -DHAVE_REGCOMP=1
endif
ifdef HAVE_INETNTOA_R
  BBS_O_CFLAGS += -DHAVE_INETNTOA_R=1
endif
ifdef HAVE_LINGER_STRUCT
  BBS_O_CFLAGS += -DHAVE_LINGER_STRUCT=1
endif

BBS_CFLAGS = $(BBS_O_CFLAGS) $(BBS_OPT_CFLAGS)
BBS_LDFLAGS = $(BBS_O_LDFLAGS) $(BBS_OPT_LDFLAGS)
QA_LDFLAGS = $(QA_O_LDFLAGS) $(QA_OPT_LDFLAGS)
TOOLS_CFLAGS = -DBBS_SYSLOG_FACILITY=$(BBS_SYSLOG_FACILITY)
